import { PrismaClient } from '@prisma/client'

const db = new PrismaClient()

async function seed() {
  console.log('🌱 Seeding NomadMY database...')

  // Clear existing data
  await db.wifiMetric.deleteMany()
  await db.transitAccess.deleteMany()
  await db.venueCost.deleteMany()
  await db.workProfile.deleteMany()
  await db.location.deleteMany()

  const locations = [
    // ─── Kuala Lumpur ─────────────────────────────────────────────
    {
      name: "Common Ground Tropical City",
      googlePlaceId: "ChIJW4V8UxRJzDERRh6WkMuYHjg",
      formattedAddress: "G-03, Oasis Square, No. 2, Jalan PJU 6/2, Oasis Boulevard, 47400 Petaling Jaya, Selangor",
      category: "coworking",
      state: "Selangor",
      area: "Petaling Jaya",
      latitude: 3.1075,
      longitude: 101.6168,
      googleRating: 4.4,
      googleUserRatingsTotal: 283,
      googleMapsUrl: "https://maps.google.com/?cid=1234567890",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
      },
      venueCost: { coffeePriceMyr: 14.00, dayPassMyr: 45.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 185, uploadMbps: 92, pingMs: 8 },
        { downloadMbps: 210, uploadMbps: 105, pingMs: 6 },
      ],
      transit: [
        { nearestStationName: "Taman Jaya LRT", stationLine: "LRT Kelana Jaya Line", walkTimeMins: 7, distanceMeters: 450 },
      ],
    },
    {
      name: "WORQ Coworking Space KL Sentral",
      googlePlaceId: "ChIJ3zurT8lJzDEREqRv6FvZBiI",
      formattedAddress: "Level 2, Nu Sentral, Jalan Tun Sambanthan, 50470 Kuala Lumpur",
      category: "coworking",
      state: "Kuala Lumpur",
      area: "KL Sentral",
      latitude: 3.1333,
      longitude: 101.6867,
      googleRating: 4.5,
      googleUserRatingsTotal: 542,
      googleMapsUrl: "https://maps.google.com/?cid=2345678901",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
      },
      venueCost: { coffeePriceMyr: 12.00, dayPassMyr: 55.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 250, uploadMbps: 120, pingMs: 5 },
      ],
      transit: [
        { nearestStationName: "KL Sentral", stationLine: "KTM / LRT / Monorail / MRT", walkTimeMins: 2, distanceMeters: 120 },
      ],
    },
    {
      name: "VCR Coffee",
      googlePlaceId: "ChIJd2R-L8tJzDER8FvJFWSWHuE",
      formattedAddress: "21, Jalan Rembia, Off Jalan Telawi, Bangsar, 59000 Kuala Lumpur",
      category: "cafe",
      state: "Kuala Lumpur",
      area: "Bangsar",
      latitude: 3.1254,
      longitude: 101.6724,
      googleRating: 4.3,
      googleUserRatingsTotal: 1856,
      googleMapsUrl: "https://maps.google.com/?cid=3456789012",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "casual_sofa",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 16.00, dayPassMyr: null, minSpendMyr: 15.00 },
      wifiMetrics: [
        { downloadMbps: 65, uploadMbps: 28, pingMs: 18 },
      ],
      transit: [
        { nearestStationName: "Bangsar LRT", stationLine: "LRT Kelana Jaya Line", walkTimeMins: 5, distanceMeters: 350 },
      ],
    },
    {
      name: "PULP by Papa Palheta",
      googlePlaceId: "ChIJM6k1QstJzDERhyjW9UNjYGM",
      formattedAddress: "LG-3, The Waterfront @ ParkCity, Desa ParkCity, 52200 Kuala Lumpur",
      category: "cafe",
      state: "Kuala Lumpur",
      area: "Desa ParkCity",
      latitude: 3.1912,
      longitude: 101.6211,
      googleRating: 4.5,
      googleUserRatingsTotal: 2103,
      googleMapsUrl: "https://maps.google.com/?cid=4567890123",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 14.50, dayPassMyr: null, minSpendMyr: 12.00 },
      wifiMetrics: [
        { downloadMbps: 78, uploadMbps: 35, pingMs: 14 },
      ],
      transit: [],
    },
    {
      name: "The Breakfast Grid",
      googlePlaceId: "ChIJM2KURM1JzDERrE-6Th4yXiE",
      formattedAddress: "17, Jalan Telawi 3, Bangsar Baru, 59000 Kuala Lumpur",
      category: "cafe",
      state: "Kuala Lumpur",
      area: "Bangsar",
      latitude: 3.1271,
      longitude: 101.6732,
      googleRating: 4.2,
      googleUserRatingsTotal: 987,
      googleMapsUrl: "https://maps.google.com/?cid=5678901234",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 15.00, dayPassMyr: null, minSpendMyr: 18.00 },
      wifiMetrics: [
        { downloadMbps: 55, uploadMbps: 22, pingMs: 22 },
      ],
      transit: [
        { nearestStationName: "Bangsar LRT", stationLine: "LRT Kelana Jaya Line", walkTimeMins: 6, distanceMeters: 420 },
      ],
    },
    {
      name: "Co-labs Coworking Desa ParkCity",
      googlePlaceId: "ChIJwzQUzt1JzDERxQkSGCpCzVQ",
      formattedAddress: "The Waterfront @ ParkCity, Desa ParkCity, 52200 Kuala Lumpur",
      category: "coworking",
      state: "Kuala Lumpur",
      area: "Desa ParkCity",
      latitude: 3.1905,
      longitude: 101.6218,
      googleRating: 4.6,
      googleUserRatingsTotal: 134,
      googleMapsUrl: "https://maps.google.com/?cid=6789012345",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
      },
      venueCost: { coffeePriceMyr: 12.00, dayPassMyr: 50.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 200, uploadMbps: 100, pingMs: 7 },
      ],
      transit: [],
    },
    {
      name: "KL Library (Perpustakaan KL)",
      googlePlaceId: "ChIJo-9_YMlJzDER_ZMHlEpk1QI",
      formattedAddress: "Jalan Raja, 50050 Kuala Lumpur",
      category: "public_space",
      state: "Kuala Lumpur",
      area: "Kuala Lumpur City Centre",
      latitude: 3.1489,
      longitude: 101.6953,
      googleRating: 4.3,
      googleUserRatingsTotal: 4521,
      googleMapsUrl: "https://maps.google.com/?cid=7890123456",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "silent",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 5.00, dayPassMyr: null, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 120, uploadMbps: 60, pingMs: 10 },
      ],
      transit: [
        { nearestStationName: "Masjid Jamek LRT", stationLine: "LRT Kelana Jaya / Ampang Line", walkTimeMins: 5, distanceMeters: 350 },
        { nearestStationName: "Merdeka MRT", stationLine: "MRT Kajang Line", walkTimeMins: 8, distanceMeters: 600 },
      ],
    },
    {
      name: "Nexco Coworking Space",
      googlePlaceId: "ChIJW-yS3s1JzDERyGUvn8i7X7A",
      formattedAddress: "L3-01, Avenue K Shopping Mall, 156 Jalan Ampang, 50450 Kuala Lumpur",
      category: "coworking",
      state: "Kuala Lumpur",
      area: "KLCC",
      latitude: 3.1598,
      longitude: 101.7133,
      googleRating: 4.4,
      googleUserRatingsTotal: 201,
      googleMapsUrl: "https://maps.google.com/?cid=8901234567",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
      },
      venueCost: { coffeePriceMyr: 13.00, dayPassMyr: 60.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 300, uploadMbps: 150, pingMs: 4 },
      ],
      transit: [
        { nearestStationName: "KLCC LRT", stationLine: "LRT Kelana Jaya Line", walkTimeMins: 3, distanceMeters: 200 },
      ],
    },
    {
      name: "Antiode Specialty Coffee",
      googlePlaceId: "ChIJ-Q52vs1JzDERP-FSJMKfYrs",
      formattedAddress: "G-06, KL Eco City, Jalan Tun Jugah, 59200 Kuala Lumpur",
      category: "cafe",
      state: "Kuala Lumpur",
      area: "Bangsar South",
      latitude: 3.1218,
      longitude: 101.6671,
      googleRating: 4.6,
      googleUserRatingsTotal: 1567,
      googleMapsUrl: "https://maps.google.com/?cid=9012345678",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 15.50, dayPassMyr: null, minSpendMyr: 15.00 },
      wifiMetrics: [
        { downloadMbps: 85, uploadMbps: 40, pingMs: 12 },
      ],
      transit: [
        { nearestStationName: "Bangsar South (KL Eco City)", stationLine: "MRT Kajang Line", walkTimeMins: 4, distanceMeters: 280 },
      ],
    },
    {
      name: "LOKL Coffee Co.",
      googlePlaceId: "ChIJd25KBMtJzDERO-J8iE-xvfk",
      formattedAddress: "21, Jalan Tun H S Lee, City Centre, 50000 Kuala Lumpur",
      category: "cafe",
      state: "Kuala Lumpur",
      area: "Chinatown / CBD",
      latitude: 3.1472,
      longitude: 101.6968,
      googleRating: 4.4,
      googleUserRatingsTotal: 3210,
      googleMapsUrl: "https://maps.google.com/?cid=0123456789",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "time_limited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 16.00, dayPassMyr: null, minSpendMyr: 18.00 },
      wifiMetrics: [
        { downloadMbps: 58, uploadMbps: 25, pingMs: 20 },
      ],
      transit: [
        { nearestStationName: "Pasar Seni LRT", stationLine: "LRT Kelana Jaya / Ampang Line", walkTimeMins: 4, distanceMeters: 280 },
      ],
    },

    // ─── Penang ────────────────────────────────────────────────────
    {
      name: "The Alleycats Georgetown",
      googlePlaceId: "ChIJ-a3dMPR9zDERLaBGVSXvfkA",
      formattedAddress: "212, Lebuh Chulia, George Town, 10200 Penang",
      category: "cafe",
      state: "Penang",
      area: "Georgetown",
      latitude: 5.4155,
      longitude: 100.3422,
      googleRating: 4.2,
      googleUserRatingsTotal: 1123,
      googleMapsUrl: "https://maps.google.com/?cid=1122334455",
      isOperational: true,
      workProfile: {
        powerOutlets: "sparse",
        noiseLevel: "loud",
        seatingType: "casual_sofa",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: false,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 13.00, dayPassMyr: null, minSpendMyr: 12.00 },
      wifiMetrics: [
        { downloadMbps: 42, uploadMbps: 18, pingMs: 25 },
      ],
      transit: [],
    },
    {
      name: "Caffeine Factory",
      googlePlaceId: "ChIJXx9WMPR9zDERs3dSBBvxPLM",
      formattedAddress: "37, Jalan Bawasah, George Town, 10200 Penang",
      category: "cafe",
      state: "Penang",
      area: "Georgetown",
      latitude: 5.4192,
      longitude: 100.3388,
      googleRating: 4.5,
      googleUserRatingsTotal: 876,
      googleMapsUrl: "https://maps.google.com/?cid=2233445566",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 14.00, dayPassMyr: null, minSpendMyr: 14.00 },
      wifiMetrics: [
        { downloadMbps: 95, uploadMbps: 42, pingMs: 11 },
      ],
      transit: [],
    },
    {
      name: "Common Ground Gurney Tower",
      googlePlaceId: "ChIJTx9yNPR9zDERpGZ6QFLgxzI",
      formattedAddress: "Level 35, Gurney Tower, Persiaran Gurney, 10250 Penang",
      category: "coworking",
      state: "Penang",
      area: "Gurney Drive",
      latitude: 5.4321,
      longitude: 100.3158,
      googleRating: 4.6,
      googleUserRatingsTotal: 312,
      googleMapsUrl: "https://maps.google.com/?cid=3344556677",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
      },
      venueCost: { coffeePriceMyr: 13.00, dayPassMyr: 45.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 220, uploadMbps: 110, pingMs: 6 },
      ],
      transit: [],
    },
    {
      name: "Pocket Space Coworking",
      googlePlaceId: "ChIJFV9xOPR9zDERcTqMVhJXzQk",
      formattedAddress: "57, Jalan Nagore Road, George Town, 10200 Penang",
      category: "coworking",
      state: "Penang",
      area: "Georgetown",
      latitude: 5.4168,
      longitude: 100.3355,
      googleRating: 4.7,
      googleUserRatingsTotal: 189,
      googleMapsUrl: "https://maps.google.com/?cid=4455667788",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
      },
      venueCost: { coffeePriceMyr: 12.00, dayPassMyr: 40.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 175, uploadMbps: 88, pingMs: 8 },
      ],
      transit: [],
    },
    {
      name: "Narrow Marrow",
      googlePlaceId: "ChIJgx9wMPR9zDERyhXrWQVoXbU",
      formattedAddress: "100, Jalan Cantonment, George Town, 10450 Penang",
      category: "cafe",
      state: "Penang",
      area: "Georgetown",
      latitude: 5.4221,
      longitude: 100.3302,
      googleRating: 4.4,
      googleUserRatingsTotal: 645,
      googleMapsUrl: "https://maps.google.com/?cid=5566778899",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "quiet",
        seatingType: "casual_sofa",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 14.50, dayPassMyr: null, minSpendMyr: 15.00 },
      wifiMetrics: [
        { downloadMbps: 72, uploadMbps: 32, pingMs: 15 },
      ],
      transit: [],
    },

    // ─── Johor Bahru ──────────────────────────────────────────────
    {
      name: "WORQ Coworking JB",
      googlePlaceId: "ChIJqw9xOPR9zDERkTnFPLGvHtQ",
      formattedAddress: "Level 3, Menara Landmark, Jalan Trus, 80000 Johor Bahru",
      category: "coworking",
      state: "Johor",
      area: "Johor Bahru City",
      latitude: 1.4927,
      longitude: 103.7396,
      googleRating: 4.5,
      googleUserRatingsTotal: 198,
      googleMapsUrl: "https://maps.google.com/?cid=6677889900",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
      },
      venueCost: { coffeePriceMyr: 10.00, dayPassMyr: 35.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 160, uploadMbps: 80, pingMs: 9 },
      ],
      transit: [],
    },
    {
      name: "The Replacement Lodge",
      googlePlaceId: "ChIJ-x9wOPR9zDERdTknFHPLGvH",
      formattedAddress: "33, Jalan Dhoby, 80000 Johor Bahru",
      category: "cafe",
      state: "Johor",
      area: "Johor Bahru City",
      latitude: 1.4912,
      longitude: 103.7412,
      googleRating: 4.3,
      googleUserRatingsTotal: 754,
      googleMapsUrl: "https://maps.google.com/?cid=7788990011",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 12.00, dayPassMyr: null, minSpendMyr: 10.00 },
      wifiMetrics: [
        { downloadMbps: 68, uploadMbps: 30, pingMs: 18 },
      ],
      transit: [],
    },
    {
      name: "Flavours at Anns (Co-Living Cafe)",
      googlePlaceId: "ChIJRxy9OPR9zDERdTkJFPLGvH",
      formattedAddress: "1-2, Jalan Kolam Air, 80100 Johor Bahru",
      category: "cafe",
      state: "Johor",
      area: "Tebrau",
      latitude: 1.5035,
      longitude: 103.7568,
      googleRating: 4.1,
      googleUserRatingsTotal: 523,
      googleMapsUrl: "https://maps.google.com/?cid=8899001122",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "quiet",
        seatingType: "casual_sofa",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 11.00, dayPassMyr: null, minSpendMyr: 10.00 },
      wifiMetrics: [
        { downloadMbps: 55, uploadMbps: 24, pingMs: 20 },
      ],
      transit: [],
    },

    // ─── Melaka ────────────────────────────────────────────────────
    {
      name: "Calanthe Art Cafe",
      googlePlaceId: "ChIJ-x9wOPR9zDERdTkJFPLGvH",
      formattedAddress: "13, Jalan Hang Kasturi, 75200 Melaka",
      category: "cafe",
      state: "Melaka",
      area: "Melaka Raya",
      latitude: 2.1912,
      longitude: 102.2508,
      googleRating: 4.3,
      googleUserRatingsTotal: 1890,
      googleMapsUrl: "https://maps.google.com/?cid=9900112233",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 12.00, dayPassMyr: null, minSpendMyr: 12.00 },
      wifiMetrics: [
        { downloadMbps: 48, uploadMbps: 20, pingMs: 22 },
      ],
      transit: [],
    },
    {
      name: "The Stamps Hotel & Cafe",
      googlePlaceId: "ChIJGy9wOPR9zDERdTkJFPLGvH",
      formattedAddress: "8, Jalan Kee Ann, 75000 Melaka",
      category: "cafe",
      state: "Melaka",
      area: "Melaka City",
      latitude: 2.1963,
      longitude: 102.2535,
      googleRating: 4.4,
      googleUserRatingsTotal: 678,
      googleMapsUrl: "https://maps.google.com/?cid=0011223344",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "quiet",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 13.00, dayPassMyr: null, minSpendMyr: 10.00 },
      wifiMetrics: [
        { downloadMbps: 52, uploadMbps: 22, pingMs: 19 },
      ],
      transit: [],
    },

    // ─── Selangor ──────────────────────────────────────────────────
    {
      name: "Spaces Sunway",
      googlePlaceId: "ChIJgT9xOPR9zDERdTkJFPLGvH",
      formattedAddress: "Tower 3, Level 6, Sunway Pyramid Tower, Bandar Sunway, 47500 Selangor",
      category: "coworking",
      state: "Selangor",
      area: "Bandar Sunway",
      latitude: 3.0728,
      longitude: 101.6072,
      googleRating: 4.3,
      googleUserRatingsTotal: 267,
      googleMapsUrl: "https://maps.google.com/?cid=1122334400",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
      },
      venueCost: { coffeePriceMyr: 12.00, dayPassMyr: 50.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 195, uploadMbps: 98, pingMs: 7 },
      ],
      transit: [
        { nearestStationName: "USJ 7 LRT", stationLine: "LRT Kelana Jaya Line", walkTimeMins: 8, distanceMeters: 550 },
      ],
    },
    {
      name: "Coffeebean Xchange",
      googlePlaceId: "ChIJwU9xOPR9zDERdTkJFPLGvH",
      formattedAddress: "G-05, Empire Damansara, Jalan PJU 8/1, 47820 Petaling Jaya",
      category: "cafe",
      state: "Selangor",
      area: "Damansara Perdana",
      latitude: 3.1561,
      longitude: 101.6008,
      googleRating: 4.1,
      googleUserRatingsTotal: 432,
      googleMapsUrl: "https://maps.google.com/?cid=2233445500",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 14.00, dayPassMyr: null, minSpendMyr: 15.00 },
      wifiMetrics: [
        { downloadMbps: 75, uploadMbps: 33, pingMs: 13 },
      ],
      transit: [],
    },

    // ─── Sabah (Kota Kinabalu) ─────────────────────────────────────
    {
      name: "Green Table Coffee",
      googlePlaceId: "ChIJiT9xOPR9zDERdTkJFPLGvH",
      formattedAddress: "Lot 21, GFS, Api-Api Centre, Jalan Datuk Peter Mojuntin, 88000 Kota Kinabalu",
      category: "cafe",
      state: "Sabah",
      area: "Kota Kinabalu",
      latitude: 5.9804,
      longitude: 116.0735,
      googleRating: 4.4,
      googleUserRatingsTotal: 567,
      googleMapsUrl: "https://maps.google.com/?cid=3344556600",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "quiet",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 12.00, dayPassMyr: null, minSpendMyr: 10.00 },
      wifiMetrics: [
        { downloadMbps: 60, uploadMbps: 28, pingMs: 16 },
      ],
      transit: [],
    },
    {
      name: "Moomin Cafe Kota Kinabalu",
      googlePlaceId: "ChIJRU9xOPR9zDERdTkJFPLGvH",
      formattedAddress: "G-06, Imago Shopping Mall, Jalan Tun Fuad Stephens, 88000 Kota Kinabalu",
      category: "cafe",
      state: "Sabah",
      area: "Kota Kinabalu",
      latitude: 5.9828,
      longitude: 116.0758,
      googleRating: 4.2,
      googleUserRatingsTotal: 345,
      googleMapsUrl: "https://maps.google.com/?cid=4455667700",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "casual_sofa",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 14.00, dayPassMyr: null, minSpendMyr: 15.00 },
      wifiMetrics: [
        { downloadMbps: 50, uploadMbps: 22, pingMs: 18 },
      ],
      transit: [],
    },

    // ─── Sarawak (Kuching) ─────────────────────────────────────────
    {
      "name": "The Junk",
      "googlePlaceId": "ChIJiS9xOPR9zDERdTkJFPLGvH",
      "formattedAddress": "26, Jalan Wayang, 93000 Kuching, Sarawak",
      "category": "cafe",
      "state": "Sarawak",
      "area": "Kuching",
      "latitude": 1.5592,
      "longitude": 110.3592,
      "googleRating": 4.5,
      "googleUserRatingsTotal": 432,
      "googleMapsUrl": "https://maps.google.com/?cid=5566778800",
      "isOperational": true,
      "workProfile": {
        "powerOutlets": "moderate",
        "noiseLevel": "quiet",
        "seatingType": "standard",
        "laptopPolicy": "friendly_unlimited",
        "hasAirCon": true,
        "callFriendly": false,
      },
      "venueCost": { "coffeePriceMyr": 11.00, "dayPassMyr": null, "minSpendMyr": 10.00 },
      "wifiMetrics": [
        { "downloadMbps": 45, "uploadMbps": 20, "pingMs": 24 },
      ],
      "transit": [],
    },
  ]

  for (const loc of locations) {
    const location = await db.location.create({
      data: {
        googlePlaceId: loc.googlePlaceId,
        name: loc.name,
        formattedAddress: loc.formattedAddress,
        category: loc.category,
        state: loc.state,
        area: loc.area,
        latitude: loc.latitude,
        longitude: loc.longitude,
        googleRating: loc.googleRating,
        googleUserRatingsTotal: loc.googleUserRatingsTotal,
        googleMapsUrl: loc.googleMapsUrl,
        isOperational: loc.isOperational,
        workProfile: {
          create: loc.workProfile,
        },
        venueCost: loc.venueCost ? {
          create: loc.venueCost,
        } : undefined,
      },
    })

    // Seed Wi-Fi metrics
    for (const wm of loc.wifiMetrics) {
      await db.wifiMetric.create({
        data: {
          locationId: location.id,
          ...wm,
        },
      })
    }

    // Seed transit links
    for (const tr of loc.transit) {
      await db.transitAccess.create({
        data: {
          locationId: location.id,
          ...tr,
        },
      })
    }
  }

  console.log(`✅ Seeded ${locations.length} locations across Malaysia`)
  console.log('📍 States covered:', [...new Set(locations.map(l => l.state))].join(', '))
}

seed()
  .catch(console.error)
  .finally(() => db.$disconnect())
