import { PrismaClient } from '@prisma/client'

const db = new PrismaClient()

async function seed() {
  console.log('🌱 Seeding NomadMY database...')

  // Clear existing data
  await db.wifiMetric.deleteMany()
  await db.transitAccess.deleteMany()
  await db.venueCost.deleteMany()
  await db.workProfile.deleteMany()
  await db.location.deleteMany()

  const locations = [
    // ─── Kuala Lumpur ─────────────────────────────────────────────
    {
      name: "Common Ground Tropical City",
      googlePlaceId: "ChIJW4V8UxRJzDERRh6WkMuYHjg",
      formattedAddress: "G-03, Oasis Square, No. 2, Jalan PJU 6/2, Oasis Boulevard, 47400 Petaling Jaya, Selangor",
      category: "coworking",
      state: "Selangor",
      district: "Petaling",
      area: "Petaling Jaya",
      latitude: 3.1075,
      longitude: 101.6168,
      googleRating: 4.4,
      googleUserRatingsTotal: 283,
      googleMapsUrl: "https://maps.google.com/?cid=1234567890",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
      },
      venueCost: { coffeePriceMyr: 14.00, dayPassMyr: 45.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 185, uploadMbps: 92, pingMs: 8 },
        { downloadMbps: 210, uploadMbps: 105, pingMs: 6 },
      ],
      transit: [
        { nearestStationName: "Taman Jaya LRT", stationLine: "LRT Kelana Jaya Line", walkTimeMins: 7, distanceMeters: 450 },
      ],
    },
    {
      name: "WORQ Coworking Space KL Sentral",
      googlePlaceId: "ChIJ3zurT8lJzDEREqRv6FvZBiI",
      formattedAddress: "Level 2, Nu Sentral, Jalan Tun Sambanthan, 50470 Kuala Lumpur",
      category: "coworking",
      state: "Kuala Lumpur",
      district: "Kuala Lumpur",
      area: "KL Sentral",
      latitude: 3.1333,
      longitude: 101.6867,
      googleRating: 4.5,
      googleUserRatingsTotal: 542,
      googleMapsUrl: "https://maps.google.com/?cid=2345678901",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
      },
      venueCost: { coffeePriceMyr: 12.00, dayPassMyr: 55.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 250, uploadMbps: 120, pingMs: 5 },
      ],
      transit: [
        { nearestStationName: "KL Sentral", stationLine: "KTM / LRT / Monorail / MRT", walkTimeMins: 2, distanceMeters: 120 },
      ],
    },
    {
      name: "VCR Coffee",
      googlePlaceId: "ChIJd2R-L8tJzDER8FvJFWSWHuE",
      formattedAddress: "21, Jalan Rembia, Off Jalan Telawi, Bangsar, 59000 Kuala Lumpur",
      category: "cafe",
      state: "Kuala Lumpur",
      district: "Kuala Lumpur",
      area: "Bangsar",
      latitude: 3.1254,
      longitude: 101.6724,
      googleRating: 4.3,
      googleUserRatingsTotal: 1856,
      googleMapsUrl: "https://maps.google.com/?cid=3456789012",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "casual_sofa",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 16.00, dayPassMyr: null, minSpendMyr: 15.00 },
      wifiMetrics: [
        { downloadMbps: 65, uploadMbps: 28, pingMs: 18 },
      ],
      transit: [
        { nearestStationName: "Bangsar LRT", stationLine: "LRT Kelana Jaya Line", walkTimeMins: 5, distanceMeters: 350 },
      ],
    },
    {
      name: "PULP by Papa Palheta",
      googlePlaceId: "ChIJM6k1QstJzDERhyjW9UNjYGM",
      formattedAddress: "LG-3, The Waterfront @ ParkCity, Desa ParkCity, 52200 Kuala Lumpur",
      category: "cafe",
      state: "Kuala Lumpur",
      district: "Kuala Lumpur",
      area: "Desa ParkCity",
      latitude: 3.1912,
      longitude: 101.6211,
      googleRating: 4.5,
      googleUserRatingsTotal: 2103,
      googleMapsUrl: "https://maps.google.com/?cid=4567890123",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 14.50, dayPassMyr: null, minSpendMyr: 12.00 },
      wifiMetrics: [
        { downloadMbps: 78, uploadMbps: 35, pingMs: 14 },
      ],
      transit: [],
    },
    {
      name: "The Breakfast Grid",
      googlePlaceId: "ChIJM2KURM1JzDERrE-6Th4yXiE",
      formattedAddress: "17, Jalan Telawi 3, Bangsar Baru, 59000 Kuala Lumpur",
      category: "cafe",
      state: "Kuala Lumpur",
      district: "Kuala Lumpur",
      area: "Bangsar",
      latitude: 3.1271,
      longitude: 101.6732,
      googleRating: 4.2,
      googleUserRatingsTotal: 987,
      googleMapsUrl: "https://maps.google.com/?cid=5678901234",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 15.00, dayPassMyr: null, minSpendMyr: 18.00 },
      wifiMetrics: [
        { downloadMbps: 55, uploadMbps: 22, pingMs: 22 },
      ],
      transit: [
        { nearestStationName: "Bangsar LRT", stationLine: "LRT Kelana Jaya Line", walkTimeMins: 6, distanceMeters: 420 },
      ],
    },
    {
      name: "Co-labs Coworking Desa ParkCity",
      googlePlaceId: "ChIJwzQUzt1JzDERxQkSGCpCzVQ",
      formattedAddress: "The Waterfront @ ParkCity, Desa ParkCity, 52200 Kuala Lumpur",
      category: "coworking",
      state: "Kuala Lumpur",
      district: "Kuala Lumpur",
      area: "Desa ParkCity",
      latitude: 3.1905,
      longitude: 101.6218,
      googleRating: 4.6,
      googleUserRatingsTotal: 134,
      googleMapsUrl: "https://maps.google.com/?cid=6789012345",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
      },
      venueCost: { coffeePriceMyr: 12.00, dayPassMyr: 50.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 200, uploadMbps: 100, pingMs: 7 },
      ],
      transit: [],
    },
    {
      name: "KL Library (Perpustakaan KL)",
      googlePlaceId: "ChIJo-9_YMlJzDER_ZMHlEpk1QI",
      formattedAddress: "Jalan Raja, 50050 Kuala Lumpur",
      category: "public_space",
      state: "Kuala Lumpur",
      district: "Kuala Lumpur",
      area: "Kuala Lumpur City Centre",
      latitude: 3.1489,
      longitude: 101.6953,
      googleRating: 4.3,
      googleUserRatingsTotal: 4521,
      googleMapsUrl: "https://maps.google.com/?cid=7890123456",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "silent",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 5.00, dayPassMyr: null, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 120, uploadMbps: 60, pingMs: 10 },
      ],
      transit: [
        { nearestStationName: "Masjid Jamek LRT", stationLine: "LRT Kelana Jaya / Ampang Line", walkTimeMins: 5, distanceMeters: 350 },
        { nearestStationName: "Merdeka MRT", stationLine: "MRT Kajang Line", walkTimeMins: 8, distanceMeters: 600 },
      ],
    },
    {
      name: "Nexco Coworking Space",
      googlePlaceId: "ChIJW-yS3s1JzDERyGUvn8i7X7A",
      formattedAddress: "L3-01, Avenue K Shopping Mall, 156 Jalan Ampang, 50450 Kuala Lumpur",
      category: "coworking",
      state: "Kuala Lumpur",
      district: "Kuala Lumpur",
      area: "KLCC",
      latitude: 3.1598,
      longitude: 101.7133,
      googleRating: 4.4,
      googleUserRatingsTotal: 201,
      googleMapsUrl: "https://maps.google.com/?cid=8901234567",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
      },
      venueCost: { coffeePriceMyr: 13.00, dayPassMyr: 60.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 300, uploadMbps: 150, pingMs: 4 },
      ],
      transit: [
        { nearestStationName: "KLCC LRT", stationLine: "LRT Kelana Jaya Line", walkTimeMins: 3, distanceMeters: 200 },
      ],
    },
    {
      name: "Antiode Specialty Coffee",
      googlePlaceId: "ChIJ-Q52vs1JzDERP-FSJMKfYrs",
      formattedAddress: "G-06, KL Eco City, Jalan Tun Jugah, 59200 Kuala Lumpur",
      category: "cafe",
      state: "Kuala Lumpur",
      district: "Kuala Lumpur",
      area: "Bangsar South",
      latitude: 3.1218,
      longitude: 101.6671,
      googleRating: 4.6,
      googleUserRatingsTotal: 1567,
      googleMapsUrl: "https://maps.google.com/?cid=9012345678",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 15.50, dayPassMyr: null, minSpendMyr: 15.00 },
      wifiMetrics: [
        { downloadMbps: 85, uploadMbps: 40, pingMs: 12 },
      ],
      transit: [
        { nearestStationName: "Bangsar South (KL Eco City)", stationLine: "MRT Kajang Line", walkTimeMins: 4, distanceMeters: 280 },
      ],
    },
    {
      name: "LOKL Coffee Co.",
      googlePlaceId: "ChIJd25KBMtJzDERO-J8iE-xvfk",
      formattedAddress: "21, Jalan Tun H S Lee, City Centre, 50000 Kuala Lumpur",
      category: "cafe",
      state: "Kuala Lumpur",
      district: "Kuala Lumpur",
      area: "Chinatown / CBD",
      latitude: 3.1472,
      longitude: 101.6968,
      googleRating: 4.4,
      googleUserRatingsTotal: 3210,
      googleMapsUrl: "https://maps.google.com/?cid=0123456789",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "time_limited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 16.00, dayPassMyr: null, minSpendMyr: 18.00 },
      wifiMetrics: [
        { downloadMbps: 58, uploadMbps: 25, pingMs: 20 },
      ],
      transit: [
        { nearestStationName: "Pasar Seni LRT", stationLine: "LRT Kelana Jaya / Ampang Line", walkTimeMins: 4, distanceMeters: 280 },
      ],
    },

    // ─── Penang ────────────────────────────────────────────────────
    {
      name: "The Alleycats Georgetown",
      googlePlaceId: "ChIJ-a3dMPR9zDERLaBGVSXvfkA",
      formattedAddress: "212, Lebuh Chulia, George Town, 10200 Penang",
      category: "cafe",
      state: "Penang",
      district: "Timur Laut",
      area: "Georgetown",
      latitude: 5.4155,
      longitude: 100.3422,
      googleRating: 4.2,
      googleUserRatingsTotal: 1123,
      googleMapsUrl: "https://maps.google.com/?cid=1122334455",
      isOperational: true,
      workProfile: {
        powerOutlets: "sparse",
        noiseLevel: "loud",
        seatingType: "casual_sofa",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: false,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 13.00, dayPassMyr: null, minSpendMyr: 12.00 },
      wifiMetrics: [
        { downloadMbps: 42, uploadMbps: 18, pingMs: 25 },
      ],
      transit: [],
    },
    {
      name: "Caffeine Factory",
      googlePlaceId: "ChIJXx9WMPR9zDERs3dSBBvxPLM",
      formattedAddress: "37, Jalan Bawasah, George Town, 10200 Penang",
      category: "cafe",
      state: "Penang",
      district: "Timur Laut",
      area: "Georgetown",
      latitude: 5.4192,
      longitude: 100.3388,
      googleRating: 4.5,
      googleUserRatingsTotal: 876,
      googleMapsUrl: "https://maps.google.com/?cid=2233445566",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 14.00, dayPassMyr: null, minSpendMyr: 14.00 },
      wifiMetrics: [
        { downloadMbps: 95, uploadMbps: 42, pingMs: 11 },
      ],
      transit: [],
    },
    {
      name: "Common Ground Gurney Tower",
      googlePlaceId: "ChIJTx9yNPR9zDERpGZ6QFLgxzI",
      formattedAddress: "Level 35, Gurney Tower, Persiaran Gurney, 10250 Penang",
      category: "coworking",
      state: "Penang",
      district: "Timur Laut",
      area: "Gurney Drive",
      latitude: 5.4321,
      longitude: 100.3158,
      googleRating: 4.6,
      googleUserRatingsTotal: 312,
      googleMapsUrl: "https://maps.google.com/?cid=3344556677",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
      },
      venueCost: { coffeePriceMyr: 13.00, dayPassMyr: 45.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 220, uploadMbps: 110, pingMs: 6 },
      ],
      transit: [],
    },
    {
      name: "Pocket Space Coworking",
      googlePlaceId: "ChIJFV9xOPR9zDERcTqMVhJXzQk",
      formattedAddress: "57, Jalan Nagore Road, George Town, 10200 Penang",
      category: "coworking",
      state: "Penang",
      district: "Timur Laut",
      area: "Georgetown",
      latitude: 5.4168,
      longitude: 100.3355,
      googleRating: 4.7,
      googleUserRatingsTotal: 189,
      googleMapsUrl: "https://maps.google.com/?cid=4455667788",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
      },
      venueCost: { coffeePriceMyr: 12.00, dayPassMyr: 40.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 175, uploadMbps: 88, pingMs: 8 },
      ],
      transit: [],
    },
    {
      name: "Narrow Marrow",
      googlePlaceId: "ChIJgx9wMPR9zDERyhXrWQVoXbU",
      formattedAddress: "100, Jalan Cantonment, George Town, 10450 Penang",
      category: "cafe",
      state: "Penang",
      district: "Timur Laut",
      area: "Georgetown",
      latitude: 5.4221,
      longitude: 100.3302,
      googleRating: 4.4,
      googleUserRatingsTotal: 645,
      googleMapsUrl: "https://maps.google.com/?cid=5566778899",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "quiet",
        seatingType: "casual_sofa",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 14.50, dayPassMyr: null, minSpendMyr: 15.00 },
      wifiMetrics: [
        { downloadMbps: 72, uploadMbps: 32, pingMs: 15 },
      ],
      transit: [],
    },

    // ─── Johor Bahru ──────────────────────────────────────────────
    {
      name: "WORQ Coworking JB",
      googlePlaceId: "ChIJqw9xOPR9zDERkTnFPLGvHtQ",
      formattedAddress: "Level 3, Menara Landmark, Jalan Trus, 80000 Johor Bahru",
      category: "coworking",
      state: "Johor",
      district: "Johor Bahru",
      area: "Johor Bahru City",
      latitude: 1.4927,
      longitude: 103.7396,
      googleRating: 4.5,
      googleUserRatingsTotal: 198,
      googleMapsUrl: "https://maps.google.com/?cid=6677889900",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
      },
      venueCost: { coffeePriceMyr: 10.00, dayPassMyr: 35.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 160, uploadMbps: 80, pingMs: 9 },
      ],
      transit: [],
    },
    {
      name: "The Replacement Lodge",
      googlePlaceId: "ChIJ-x9wOPR9zDERdTknFHPLGvH",
      formattedAddress: "33, Jalan Dhoby, 80000 Johor Bahru",
      category: "cafe",
      state: "Johor",
      district: "Johor Bahru",
      area: "Johor Bahru City",
      latitude: 1.4912,
      longitude: 103.7412,
      googleRating: 4.3,
      googleUserRatingsTotal: 754,
      googleMapsUrl: "https://maps.google.com/?cid=7788990011",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 12.00, dayPassMyr: null, minSpendMyr: 10.00 },
      wifiMetrics: [
        { downloadMbps: 68, uploadMbps: 30, pingMs: 18 },
      ],
      transit: [],
    },
    {
      name: "Flavours at Anns (Co-Living Cafe)",
      googlePlaceId: "ChIJRxy9OPR9zDERdTkJFPLGvH",
      formattedAddress: "1-2, Jalan Kolam Air, 80100 Johor Bahru",
      category: "cafe",
      state: "Johor",
      district: "Johor Bahru",
      area: "Tebrau",
      latitude: 1.5035,
      longitude: 103.7568,
      googleRating: 4.1,
      googleUserRatingsTotal: 523,
      googleMapsUrl: "https://maps.google.com/?cid=8899001122",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "quiet",
        seatingType: "casual_sofa",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 11.00, dayPassMyr: null, minSpendMyr: 10.00 },
      wifiMetrics: [
        { downloadMbps: 55, uploadMbps: 24, pingMs: 20 },
      ],
      transit: [],
    },

    // ─── Melaka ────────────────────────────────────────────────────
    {
      name: "Calanthe Art Cafe",
      googlePlaceId: "ChIJ-x9wOPR9zDERdTkJFPLGvH",
      formattedAddress: "13, Jalan Hang Kasturi, 75200 Melaka",
      category: "cafe",
      state: "Melaka",
      district: "Melaka Tengah",
      area: "Melaka Raya",
      latitude: 2.1912,
      longitude: 102.2508,
      googleRating: 4.3,
      googleUserRatingsTotal: 1890,
      googleMapsUrl: "https://maps.google.com/?cid=9900112233",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 12.00, dayPassMyr: null, minSpendMyr: 12.00 },
      wifiMetrics: [
        { downloadMbps: 48, uploadMbps: 20, pingMs: 22 },
      ],
      transit: [],
    },
    {
      name: "The Stamps Hotel & Cafe",
      googlePlaceId: "ChIJGy9wOPR9zDERdTkJFPLGvH",
      formattedAddress: "8, Jalan Kee Ann, 75000 Melaka",
      category: "cafe",
      state: "Melaka",
      district: "Melaka Tengah",
      area: "Melaka City",
      latitude: 2.1963,
      longitude: 102.2535,
      googleRating: 4.4,
      googleUserRatingsTotal: 678,
      googleMapsUrl: "https://maps.google.com/?cid=0011223344",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "quiet",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 13.00, dayPassMyr: null, minSpendMyr: 10.00 },
      wifiMetrics: [
        { downloadMbps: 52, uploadMbps: 22, pingMs: 19 },
      ],
      transit: [],
    },

    // ─── Selangor ──────────────────────────────────────────────────
    {
      name: "Spaces Sunway",
      googlePlaceId: "ChIJgT9xOPR9zDERdTkJFPLGvH",
      formattedAddress: "Tower 3, Level 6, Sunway Pyramid Tower, Bandar Sunway, 47500 Selangor",
      category: "coworking",
      state: "Selangor",
      district: "Petaling",
      area: "Bandar Sunway",
      latitude: 3.0728,
      longitude: 101.6072,
      googleRating: 4.3,
      googleUserRatingsTotal: 267,
      googleMapsUrl: "https://maps.google.com/?cid=1122334400",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
      },
      venueCost: { coffeePriceMyr: 12.00, dayPassMyr: 50.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 195, uploadMbps: 98, pingMs: 7 },
      ],
      transit: [
        { nearestStationName: "USJ 7 LRT", stationLine: "LRT Kelana Jaya Line", walkTimeMins: 8, distanceMeters: 550 },
      ],
    },
    {
      name: "Coffeebean Xchange",
      googlePlaceId: "ChIJwU9xOPR9zDERdTkJFPLGvH",
      formattedAddress: "G-05, Empire Damansara, Jalan PJU 8/1, 47820 Petaling Jaya",
      category: "cafe",
      state: "Selangor",
      district: "Petaling",
      area: "Damansara Perdana",
      latitude: 3.1561,
      longitude: 101.6008,
      googleRating: 4.1,
      googleUserRatingsTotal: 432,
      googleMapsUrl: "https://maps.google.com/?cid=2233445500",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 14.00, dayPassMyr: null, minSpendMyr: 15.00 },
      wifiMetrics: [
        { downloadMbps: 75, uploadMbps: 33, pingMs: 13 },
      ],
      transit: [],
    },

    // ─── Sabah (Kota Kinabalu) ─────────────────────────────────────
    {
      name: "Green Table Coffee",
      googlePlaceId: "ChIJiT9xOPR9zDERdTkJFPLGvH",
      formattedAddress: "Lot 21, GFS, Api-Api Centre, Jalan Datuk Peter Mojuntin, 88000 Kota Kinabalu",
      category: "cafe",
      state: "Sabah",
      district: "Kota Kinabalu",
      area: "Kota Kinabalu",
      latitude: 5.9804,
      longitude: 116.0735,
      googleRating: 4.4,
      googleUserRatingsTotal: 567,
      googleMapsUrl: "https://maps.google.com/?cid=3344556600",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "quiet",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 12.00, dayPassMyr: null, minSpendMyr: 10.00 },
      wifiMetrics: [
        { downloadMbps: 60, uploadMbps: 28, pingMs: 16 },
      ],
      transit: [],
    },
    {
      name: "Moomin Cafe Kota Kinabalu",
      googlePlaceId: "ChIJRU9xOPR9zDERdTkJFPLGvH",
      formattedAddress: "G-06, Imago Shopping Mall, Jalan Tun Fuad Stephens, 88000 Kota Kinabalu",
      category: "cafe",
      state: "Sabah",
      district: "Kota Kinabalu",
      area: "Kota Kinabalu",
      latitude: 5.9828,
      longitude: 116.0758,
      googleRating: 4.2,
      googleUserRatingsTotal: 345,
      googleMapsUrl: "https://maps.google.com/?cid=4455667700",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "casual_sofa",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 14.00, dayPassMyr: null, minSpendMyr: 15.00 },
      wifiMetrics: [
        { downloadMbps: 50, uploadMbps: 22, pingMs: 18 },
      ],
      transit: [],
    },

    // ─── Sarawak (Kuching) ─────────────────────────────────────────
    {
      "name": "The Junk",
      "googlePlaceId": "ChIJiS9xOPR9zDERdTkJFPLGvH",
      "formattedAddress": "26, Jalan Wayang, 93000 Kuching, Sarawak",
      "category": "cafe",
      "state": "Sarawak",
      "area": "Kuching",
      "latitude": 1.5592,
      "longitude": 110.3592,
      "googleRating": 4.5,
      "googleUserRatingsTotal": 432,
      "googleMapsUrl": "https://maps.google.com/?cid=5566778800",
      "isOperational": true,
      "workProfile": {
        "powerOutlets": "moderate",
        "noiseLevel": "quiet",
        "seatingType": "standard",
        "laptopPolicy": "friendly_unlimited",
        "hasAirCon": true,
        "callFriendly": false,
      },
      "venueCost": { "coffeePriceMyr": 11.00, "dayPassMyr": null, "minSpendMyr": 10.00 },
      "wifiMetrics": [
        { "downloadMbps": 45, "uploadMbps": 20, "pingMs": 24 },
      ],
      "transit": [],
    },

    // ─── Perlis (NEW) ───────────────────────────────
    {
      name: "Kopi O Kangar",
      googlePlaceId: "ChIJL8x2aWR9zDERpQnBvKm3AcI",
      formattedAddress: "32, Jalan Kangar, 01000 Kangar, Perlis",
      category: "cafe",
      state: "Perlis",
      district: "Perlis",
      area: "Kangar",
      latitude: 6.4415,
      longitude: 100.2102,
      googleRating: 4.1,
      googleUserRatingsTotal: 156,
      googleMapsUrl: "https://maps.google.com/?cid=9100000001",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "quiet",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 8.00, dayPassMyr: null, minSpendMyr: 8.00 },
      wifiMetrics: [
        { downloadMbps: 38, uploadMbps: 16, pingMs: 28 },
      ],
      transit: [],
    },

    // ─── Kedah (NEW) ───────────────────────────────
    {
      name: "The White House Coffee",
      googlePlaceId: "ChIJy3b5cXR9zDERmKjLpN2rBcI",
      formattedAddress: "88, Jalan Tunku Ibrahim, 05100 Alor Setar, Kedah",
      category: "cafe",
      state: "Kedah",
      district: "Kota Setar",
      area: "Alor Setar",
      latitude: 6.1198,
      longitude: 100.3684,
      googleRating: 4.3,
      googleUserRatingsTotal: 412,
      googleMapsUrl: "https://maps.google.com/?cid=9100000002",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "quiet",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 10.00, dayPassMyr: null, minSpendMyr: 10.00 },
      wifiMetrics: [
        { downloadMbps: 52, uploadMbps: 24, pingMs: 20 },
      ],
      transit: [
        { nearestStationName: "Stesen Keretapi Alor Setar", stationLine: "KTM ETS", walkTimeMins: 10, distanceMeters: 750 },
      ],
    },
    {
      name: "Yellow Beach Cafe",
      googlePlaceId: "ChIJk7d9eXR9zDERpN2rBcImKjL",
      formattedAddress: "Lot 12, Pantai Cenang, Mukim Kedawang, 07000 Langkawi, Kedah",
      category: "cafe",
      state: "Kedah",
      district: "Langkawi",
      area: "Langkawi",
      latitude: 6.3500,
      longitude: 99.8000,
      googleRating: 4.4,
      googleUserRatingsTotal: 1873,
      googleMapsUrl: "https://maps.google.com/?cid=9100000003",
      isOperational: true,
      workProfile: {
        powerOutlets: "sparse",
        noiseLevel: "moderate",
        seatingType: "casual_sofa",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: false,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 12.00, dayPassMyr: null, minSpendMyr: 12.00 },
      wifiMetrics: [
        { downloadMbps: 30, uploadMbps: 12, pingMs: 35 },
      ],
      transit: [],
    },

    // ─── Pahang (NEW) ───────────────────────────────
    {
      name: "Artisan Roast Kuantan",
      googlePlaceId: "ChIJw5f1gXR9zDERqN2rBcImKjL",
      formattedAddress: "15, Jalan Beserah, 25200 Kuantan, Pahang",
      category: "cafe",
      state: "Pahang",
      district: "Kuantan",
      area: "Kuantan",
      latitude: 3.8158,
      longitude: 103.3257,
      googleRating: 4.2,
      googleUserRatingsTotal: 534,
      googleMapsUrl: "https://maps.google.com/?cid=9100000004",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 11.00, dayPassMyr: null, minSpendMyr: 10.00 },
      wifiMetrics: [
        { downloadMbps: 48, uploadMbps: 22, pingMs: 22 },
        { downloadMbps: 55, uploadMbps: 26, pingMs: 18 },
      ],
      transit: [
        { nearestStationName: "Stesen KTM Kuantan", stationLine: "KTM ETS", walkTimeMins: 12, distanceMeters: 900 },
      ],
    },
    {
      name: "Perpustakaan Negeri Pahang",
      googlePlaceId: "ChIJm7h3iXR9zDERpN2rBcImKjL",
      formattedAddress: "Jalan Tun Razak, 25000 Kuantan, Pahang",
      category: "public_space",
      state: "Pahang",
      district: "Kuantan",
      area: "Kuantan",
      latitude: 3.8077,
      longitude: 103.3278,
      googleRating: 4.0,
      googleUserRatingsTotal: 210,
      googleMapsUrl: "https://maps.google.com/?cid=9100000005",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "silent",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 3.00, dayPassMyr: null, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 65, uploadMbps: 30, pingMs: 16 },
      ],
      transit: [],
    },

    // ─── Terengganu (NEW) ────────────────────────────
    {
      name: "Kopitiam Kita",
      googlePlaceId: "ChIJp9j5kXR9zDERqN2rBcImKjL",
      formattedAddress: "28, Jalan Sultan Zainal Abidin, 20000 Kuala Terengganu, Terengganu",
      category: "cafe",
      state: "Terengganu",
      district: "Kuala Terengganu",
      area: "Kuala Terengganu",
      latitude: 5.3298,
      longitude: 103.1377,
      googleRating: 4.0,
      googleUserRatingsTotal: 287,
      googleMapsUrl: "https://maps.google.com/?cid=9100000006",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 8.00, dayPassMyr: null, minSpendMyr: 8.00 },
      wifiMetrics: [
        { downloadMbps: 42, uploadMbps: 18, pingMs: 24 },
      ],
      transit: [],
    },
    {
      name: "SpaceU Coworking KT",
      googlePlaceId: "ChIJq8l6mXR9zDERpN2rBcImKjL",
      formattedAddress: "Level 2, Kompleks Perbadanan, Jalan Sultan Mahmud, 20200 Kuala Terengganu, Terengganu",
      category: "coworking",
      state: "Terengganu",
      district: "Kuala Terengganu",
      area: "Kuala Terengganu",
      latitude: 5.3325,
      longitude: 103.1420,
      googleRating: 4.3,
      googleUserRatingsTotal: 78,
      googleMapsUrl: "https://maps.google.com/?cid=9100000007",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
      },
      venueCost: { coffeePriceMyr: 9.00, dayPassMyr: 30.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 120, uploadMbps: 55, pingMs: 12 },
      ],
      transit: [],
    },

    // ─── Negeri Sembilan (NEW) ───────────────────────
    {
      name: "N9 Coffee House",
      googlePlaceId: "ChIJs2m7nXR9zDERqN2rBcImKjL",
      formattedAddress: "G-08, The Centrepoint, Jalan Taman Seremban Jaya, 70300 Seremban, Negeri Sembilan",
      category: "cafe",
      state: "Negeri Sembilan",
      district: "Seremban",
      area: "Seremban",
      latitude: 2.7258,
      longitude: 101.9378,
      googleRating: 4.2,
      googleUserRatingsTotal: 345,
      googleMapsUrl: "https://maps.google.com/?cid=9100000008",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "quiet",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 11.00, dayPassMyr: null, minSpendMyr: 10.00 },
      wifiMetrics: [
        { downloadMbps: 58, uploadMbps: 26, pingMs: 18 },
      ],
      transit: [
        { nearestStationName: "Stesen KTM Seremban", stationLine: "KTM Komuter", walkTimeMins: 8, distanceMeters: 550 },
      ],
    },
    {
      name: "Perpustakaan Negeri Negeri Sembilan",
      googlePlaceId: "ChIJt4o8pXR9zDERpN2rBcImKjL",
      formattedAddress: "Jalan Dato' Muda Linggi, 70000 Seremban, Negeri Sembilan",
      category: "public_space",
      state: "Negeri Sembilan",
      district: "Seremban",
      area: "Seremban",
      latitude: 2.7265,
      longitude: 101.9385,
      googleRating: 4.1,
      googleUserRatingsTotal: 189,
      googleMapsUrl: "https://maps.google.com/?cid=9100000009",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "silent",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 3.00, dayPassMyr: null, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 55, uploadMbps: 25, pingMs: 20 },
      ],
      transit: [
        { nearestStationName: "Stesen KTM Seremban", stationLine: "KTM Komuter", walkTimeMins: 6, distanceMeters: 420 },
      ],
    },

    // ─── Additional: Penang (Batu Ferringhi) ──────────
    {
      name: "Ferringhi Coffee Garden",
      googlePlaceId: "ChIJv6p9qXR9zDERqN2rBcImKjL",
      formattedAddress: "57, Jalan Batu Ferringhi, 11100 Batu Ferringhi, Penang",
      category: "cafe",
      state: "Penang",
      district: "Timur Laut",
      area: "Batu Ferringhi",
      latitude: 5.4684,
      longitude: 100.2438,
      googleRating: 4.5,
      googleUserRatingsTotal: 1423,
      googleMapsUrl: "https://maps.google.com/?cid=9100000010",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "casual_sofa",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 15.00, dayPassMyr: null, minSpendMyr: 14.00 },
      wifiMetrics: [
        { downloadMbps: 68, uploadMbps: 30, pingMs: 16 },
        { downloadMbps: 75, uploadMbps: 34, pingMs: 14 },
      ],
      transit: [],
    },

    // ─── Additional: Johor (Muar) ───────────────────
    {
      name: "Muar Riverfront Cafe",
      googlePlaceId: "ChIJw7r0sXR9zDERpN2rBcImKjL",
      formattedAddress: "12, Jalan Merdeka, 84000 Muar, Johor",
      category: "cafe",
      state: "Johor",
      district: "Muar",
      area: "Muar",
      latitude: 2.0451,
      longitude: 102.5674,
      googleRating: 4.3,
      googleUserRatingsTotal: 612,
      googleMapsUrl: "https://maps.google.com/?cid=9100000011",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "quiet",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 9.00, dayPassMyr: null, minSpendMyr: 8.00 },
      wifiMetrics: [
        { downloadMbps: 45, uploadMbps: 20, pingMs: 22 },
      ],
      transit: [
        { nearestStationName: "Stesen KTM Muar", stationLine: "KTM ETS", walkTimeMins: 10, distanceMeters: 800 },
      ],
    },

    // ─── Additional: Kuala Lumpur (Mont Kiara) ──────────
    {
      name: "The Good Space Mont Kiara",
      googlePlaceId: "ChIJx8s1tXR9zDERqN2rBcImKjL",
      formattedAddress: "Level 5, Plaza Mont Kiara, 2, Jalan Kiara, 50450 Kuala Lumpur",
      category: "coworking",
      state: "Kuala Lumpur",
      district: "Kuala Lumpur",
      area: "Mont Kiara",
      latitude: 3.1695,
      longitude: 101.6635,
      googleRating: 4.6,
      googleUserRatingsTotal: 278,
      googleMapsUrl: "https://maps.google.com/?cid=9100000012",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
      },
      venueCost: { coffeePriceMyr: 13.00, dayPassMyr: 55.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 280, uploadMbps: 140, pingMs: 4 },
        { downloadMbps: 310, uploadMbps: 155, pingMs: 3 },
      ],
      transit: [
        { nearestStationName: "Mont Kiara MRT", stationLine: "MRT Putrajaya Line", walkTimeMins: 5, distanceMeters: 350 },
      ],
    },

    // ─── Additional: Sabah (Sandakan) ───────────────
    {
      name: "Sim Sim Waterfront Cafe",
      googlePlaceId: "ChIJy9t2uXR9zDERpN2rBcImKjL",
      formattedAddress: "Lot 8, Sim Sim Road, 90000 Sandakan, Sabah",
      category: "cafe",
      state: "Sabah",
      district: "Sandakan",
      area: "Sandakan",
      latitude: 5.8402,
      longitude: 118.1179,
      googleRating: 4.1,
      googleUserRatingsTotal: 198,
      googleMapsUrl: "https://maps.google.com/?cid=9100000013",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "quiet",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 10.00, dayPassMyr: null, minSpendMyr: 10.00 },
      wifiMetrics: [
        { downloadMbps: 42, uploadMbps: 18, pingMs: 20 },
      ],
      transit: [],
    },

    // ─── Additional: Sarawak (Miri) ──────────────────
    {
      name: "Miri City Public Library",
      googlePlaceId: "ChIJz0u3vXR9zDERqN2rBcImKjL",
      formattedAddress: "Jalan Pujut, 98000 Miri, Sarawak",
      category: "public_space",
      state: "Sarawak",
      district: "Miri",
      area: "Miri",
      latitude: 4.3995,
      longitude: 114.0148,
      googleRating: 4.2,
      googleUserRatingsTotal: 267,
      googleMapsUrl: "https://maps.google.com/?cid=9100000014",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "silent",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
      },
      venueCost: { coffeePriceMyr: 3.00, dayPassMyr: null, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 50, uploadMbps: 22, pingMs: 22 },
      ],
      transit: [],
    },

    // ─── Additional: Selangor (Shah Alam) ───────────────
    {
      name: "Common Ground Shah Alam",
      googlePlaceId: "ChIJ11v4wXR9zDERpN2rBcImKjL",
      formattedAddress: "Level 8, SACC Mall, Persiaran Perbandaran, 40000 Shah Alam, Selangor",
      category: "coworking",
      state: "Selangor",
      district: "Petaling",
      area: "Shah Alam",
      latitude: 3.0733,
      longitude: 101.5185,
      googleRating: 4.5,
      googleUserRatingsTotal: 195,
      googleMapsUrl: "https://maps.google.com/?cid=9100000015",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
      },
      venueCost: { coffeePriceMyr: 12.00, dayPassMyr: 45.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 200, uploadMbps: 100, pingMs: 6 },
      ],
      transit: [
        { nearestStationName: "Shah Alam LRT", stationLine: "LRT Shah Alam Line", walkTimeMins: 6, distanceMeters: 420 },
      ],
    },

    // ─── Selangor — Klang District (NEW) ─────────────────────
    {
      name: "Old Town White Coffee Klang South",
      googlePlaceId: "ChIJk7m2aKL2zDERtN3rCdImKjL",
      formattedAddress: "G-08, Klang Parade, Jalan Raya Barat, 41000 Klang, Selangor",
      category: "cafe",
      state: "Selangor",
      district: "Klang",
      area: "Klang Town",
      latitude: 3.0443,
      longitude: 101.4461,
      googleRating: 4.1,
      googleUserRatingsTotal: 412,
      googleMapsUrl: "https://maps.google.com/?cid=9100000016",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
        operatingHours: "8:00-22:00",
      },
      venueCost: { coffeePriceMyr: 11.00, dayPassMyr: null, minSpendMyr: 10.00 },
      wifiMetrics: [
        { downloadMbps: 65, uploadMbps: 28, pingMs: 18 },
      ],
      transit: [
        { nearestStationName: "KTM Klang", stationLine: "KTM Port Klang Line", walkTimeMins: 10, distanceMeters: 750 },
      ],
    },
    {
      name: "Port Klang Waterfront Cafe",
      googlePlaceId: "ChIJl8n3bLM3zDERqN2rBcImKjL",
      formattedAddress: "Lot 5, Jalan Raja Tun Uda, Pelabuhan Utara, 42000 Port Klang, Selangor",
      category: "cafe",
      state: "Selangor",
      district: "Klang",
      area: "Port Klang",
      latitude: 3.0039,
      longitude: 101.3911,
      googleRating: 3.9,
      googleUserRatingsTotal: 178,
      googleMapsUrl: "https://maps.google.com/?cid=9100000017",
      isOperational: true,
      workProfile: {
        powerOutlets: "sparse",
        noiseLevel: "moderate",
        seatingType: "casual_sofa",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
        operatingHours: "9:00-21:00",
      },
      venueCost: { coffeePriceMyr: 10.00, dayPassMyr: null, minSpendMyr: 8.00 },
      wifiMetrics: [
        { downloadMbps: 45, uploadMbps: 20, pingMs: 24 },
      ],
      transit: [
        { nearestStationName: "Pelabuhan Klang KTM", stationLine: "KTM Port Klang Line", walkTimeMins: 7, distanceMeters: 500 },
      ],
    },

    // ─── Selangor — Gombak District (NEW) ────────────────────
    {
      name: "Batu Caves Heritage Cafe",
      googlePlaceId: "ChIJm9o4cLN4zDERqN2rBcImKjL",
      formattedAddress: "17, Jalan Besar Batu Caves, 68100 Batu Caves, Selangor",
      category: "cafe",
      state: "Selangor",
      district: "Gombak",
      area: "Batu Caves",
      latitude: 3.2378,
      longitude: 101.6855,
      googleRating: 4.0,
      googleUserRatingsTotal: 234,
      googleMapsUrl: "https://maps.google.com/?cid=9100000018",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
        operatingHours: "8:00-20:00",
      },
      venueCost: { coffeePriceMyr: 10.00, dayPassMyr: null, minSpendMyr: 9.00 },
      wifiMetrics: [
        { downloadMbps: 55, uploadMbps: 24, pingMs: 22 },
      ],
      transit: [
        { nearestStationName: "Batu Caves KTM", stationLine: "KTM Seremban Line", walkTimeMins: 6, distanceMeters: 400 },
      ],
    },

    // ─── Selangor — Ulu Langat District (NEW) ────────────────
    {
      name: "Common Ground Cheras",
      googlePlaceId: "ChIJn0p5dLO5zDERqN2rBcImKjL",
      formattedAddress: "Level 3, Cheras Sentral Mall, Jalan Cheras Sentral, 43200 Cheras, Selangor",
      category: "coworking",
      state: "Selangor",
      district: "Ulu Langat",
      area: "Cheras",
      latitude: 3.0648,
      longitude: 101.7517,
      googleRating: 4.5,
      googleUserRatingsTotal: 312,
      googleMapsUrl: "https://maps.google.com/?cid=9100000019",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
        operatingHours: "9:00-19:00 Mon-Fri 10:00-18:00 Sat-Sun",
      },
      venueCost: { coffeePriceMyr: 13.00, dayPassMyr: 50.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 220, uploadMbps: 110, pingMs: 6 },
        { downloadMbps: 240, uploadMbps: 120, pingMs: 5 },
      ],
      transit: [
        { nearestStationName: "Taman Mutiara MRT", stationLine: "MRT Kajang Line", walkTimeMins: 5, distanceMeters: 350 },
      ],
    },
    {
      name: "Kajang Town Heritage Coffee",
      googlePlaceId: "ChIJo1q6eLP6zDERqN2rBcImKjL",
      formattedAddress: "23, Jalan Sulaiman, 43000 Kajang, Selangor",
      category: "cafe",
      state: "Selangor",
      district: "Ulu Langat",
      area: "Kajang",
      latitude: 2.9935,
      longitude: 101.7905,
      googleRating: 4.2,
      googleUserRatingsTotal: 287,
      googleMapsUrl: "https://maps.google.com/?cid=9100000020",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
        operatingHours: "8:00-22:00",
      },
      venueCost: { coffeePriceMyr: 9.00, dayPassMyr: null, minSpendMyr: 8.00 },
      wifiMetrics: [
        { downloadMbps: 50, uploadMbps: 22, pingMs: 20 },
      ],
      transit: [
        { nearestStationName: "Kajang MRT", stationLine: "MRT Kajang Line", walkTimeMins: 8, distanceMeters: 600 },
      ],
    },

    // ─── Selangor — Sepang District (NEW) ────────────────────
    {
      name: "Cyberjaya Co-Lab",
      googlePlaceId: "ChIJp2r7fLQ7zDERqN2rBcImKjL",
      formattedAddress: "Block A, Cyberjaya City Centre, Persiaran Apec, 63000 Cyberjaya, Selangor",
      category: "coworking",
      state: "Selangor",
      district: "Sepang",
      area: "Cyberjaya",
      latitude: 2.9214,
      longitude: 101.6559,
      googleRating: 4.6,
      googleUserRatingsTotal: 198,
      googleMapsUrl: "https://maps.google.com/?cid=9100000021",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
        operatingHours: "9:00-21:00 Mon-Fri 10:00-18:00 Sat-Sun",
      },
      venueCost: { coffeePriceMyr: 14.00, dayPassMyr: 55.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 280, uploadMbps: 140, pingMs: 4 },
        { downloadMbps: 300, uploadMbps: 150, pingMs: 3 },
      ],
      transit: [
        { nearestStationName: "Cyberjaya Utama MRT", stationLine: "MRT Putrajaya Line", walkTimeMins: 6, distanceMeters: 450 },
      ],
    },

    // ─── Johor — Kulaijaya District (NEW) ────────────────────
    {
      name: "Old Town White Coffee IOI Kulai",
      googlePlaceId: "ChIJq3s8gLR8zDERqN2rBcImKjL",
      formattedAddress: "G-12, IOI Mall Kulai, Jalan Kulai, 81000 Kulai, Johor",
      category: "cafe",
      state: "Johor",
      district: "Kulaijaya",
      area: "Kulai",
      latitude: 1.6700,
      longitude: 103.6028,
      googleRating: 4.1,
      googleUserRatingsTotal: 356,
      googleMapsUrl: "https://maps.google.com/?cid=9100000022",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
        operatingHours: "8:00-22:00",
      },
      venueCost: { coffeePriceMyr: 11.00, dayPassMyr: null, minSpendMyr: 10.00 },
      wifiMetrics: [
        { downloadMbps: 60, uploadMbps: 26, pingMs: 18 },
      ],
      transit: [
        { nearestStationName: "Kulai KTM", stationLine: "KTM Tebrau Shuttle", walkTimeMins: 12, distanceMeters: 900 },
      ],
    },

    // ─── Johor — Batu Pahat District (NEW) ───────────────────
    {
      name: "Batu Pahat Riverside Cafe",
      googlePlaceId: "ChIJr4t9hLS9zDERqN2rBcImKjL",
      formattedAddress: "5, Jalan Rahmat, 83000 Batu Pahat, Johor",
      category: "cafe",
      state: "Johor",
      district: "Batu Pahat",
      area: "Batu Pahat",
      latitude: 1.8489,
      longitude: 102.9294,
      googleRating: 4.0,
      googleUserRatingsTotal: 198,
      googleMapsUrl: "https://maps.google.com/?cid=9100000023",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "quiet",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
        operatingHours: "9:00-21:00",
      },
      venueCost: { coffeePriceMyr: 9.00, dayPassMyr: null, minSpendMyr: 8.00 },
      wifiMetrics: [
        { downloadMbps: 40, uploadMbps: 18, pingMs: 24 },
      ],
      transit: [],
    },

    // ─── Johor — Kluang District (NEW) ───────────────────────
    {
      name: "Kluang Rail Coffee",
      googlePlaceId: "ChIJs5u0iLT0zDERqN2rBcImKjL",
      formattedAddress: "Platform 1, Kluang Railway Station, Jalan Stesen, 86000 Kluang, Johor",
      category: "cafe",
      state: "Johor",
      district: "Kluang",
      area: "Kluang",
      latitude: 2.0305,
      longitude: 103.3204,
      googleRating: 4.4,
      googleUserRatingsTotal: 1842,
      googleMapsUrl: "https://maps.google.com/?cid=9100000024",
      isOperational: true,
      workProfile: {
        powerOutlets: "sparse",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
        operatingHours: "7:00-18:00",
      },
      venueCost: { coffeePriceMyr: 8.00, dayPassMyr: null, minSpendMyr: 8.00 },
      wifiMetrics: [
        { downloadMbps: 35, uploadMbps: 16, pingMs: 28 },
      ],
      transit: [
        { nearestStationName: "Kluang KTM", stationLine: "KTM ETS", walkTimeMins: 1, distanceMeters: 50 },
      ],
    },

    // ─── Penang — Seberang Perai Tengah District (NEW) ───────
    {
      name: "Black Garden Coffee Bukit Mertajam",
      googlePlaceId: "ChIJt6v1jLU2zDERqN2rBcImKjL",
      formattedAddress: "28, Jalan Aston, 14000 Bukit Mertajam, Penang",
      category: "cafe",
      state: "Penang",
      district: "Seberang Perai Tengah",
      area: "Bukit Mertajam",
      latitude: 5.3647,
      longitude: 100.4619,
      googleRating: 4.3,
      googleUserRatingsTotal: 478,
      googleMapsUrl: "https://maps.google.com/?cid=9100000025",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
        operatingHours: "9:00-21:00 Mon-Fri 10:00-22:00 Sat-Sun",
      },
      venueCost: { coffeePriceMyr: 12.00, dayPassMyr: null, minSpendMyr: 12.00 },
      wifiMetrics: [
        { downloadMbps: 70, uploadMbps: 30, pingMs: 16 },
      ],
      transit: [
        { nearestStationName: "Bukit Mertajam KTM", stationLine: "KTM ETS", walkTimeMins: 8, distanceMeters: 600 },
      ],
    },

    // ─── Penang — Seberang Perai Utara District (NEW) ────────
    {
      name: "Butterworth Art Street Cafe",
      googlePlaceId: "ChIJu7w2kLV3zDERqN2rBcImKjL",
      formattedAddress: "12, Jalan Bagan Luar, 12000 Butterworth, Penang",
      category: "cafe",
      state: "Penang",
      district: "Seberang Perai Utara",
      area: "Butterworth",
      latitude: 5.3995,
      longitude: 100.3638,
      googleRating: 4.1,
      googleUserRatingsTotal: 245,
      googleMapsUrl: "https://maps.google.com/?cid=9100000026",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "casual_sofa",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
        operatingHours: "10:00-22:00",
      },
      venueCost: { coffeePriceMyr: 10.00, dayPassMyr: null, minSpendMyr: 10.00 },
      wifiMetrics: [
        { downloadMbps: 48, uploadMbps: 21, pingMs: 22 },
      ],
      transit: [
        { nearestStationName: "Butterworth KTM", stationLine: "KTM ETS / Komuter", walkTimeMins: 6, distanceMeters: 450 },
      ],
    },

    // ─── Sabah — Tawau District (NEW) ────────────────────────
    {
      name: "Tawau Harbour Cafe",
      googlePlaceId: "ChIJv8x3lLW4zDERqN2rBcImKjL",
      formattedAddress: "Lot 7, Jalan Kuhara, 91000 Tawau, Sabah",
      category: "cafe",
      state: "Sabah",
      district: "Tawau",
      area: "Tawau",
      latitude: 4.2401,
      longitude: 117.8914,
      googleRating: 4.0,
      googleUserRatingsTotal: 167,
      googleMapsUrl: "https://maps.google.com/?cid=9100000027",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
        operatingHours: "8:00-20:00",
      },
      venueCost: { coffeePriceMyr: 10.00, dayPassMyr: null, minSpendMyr: 9.00 },
      wifiMetrics: [
        { downloadMbps: 38, uploadMbps: 16, pingMs: 26 },
      ],
      transit: [],
    },

    // ─── Sabah — Penampang District (NEW) ────────────────────
    {
      name: "Penampang Digital Hub",
      googlePlaceId: "ChIJw9y4mLX5zDERqN2rBcImKjL",
      formattedAddress: "Block 2, Donggongon Town Centre, 89507 Penampang, Sabah",
      category: "coworking",
      state: "Sabah",
      district: "Penampang",
      area: "Donggongon",
      latitude: 5.9167,
      longitude: 116.1167,
      googleRating: 4.3,
      googleUserRatingsTotal: 92,
      googleMapsUrl: "https://maps.google.com/?cid=9100000028",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "ergonomic",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: true,
        operatingHours: "9:00-19:00 Mon-Fri 10:00-17:00 Sat-Sun",
      },
      venueCost: { coffeePriceMyr: 11.00, dayPassMyr: 35.00, minSpendMyr: 0 },
      wifiMetrics: [
        { downloadMbps: 150, uploadMbps: 75, pingMs: 10 },
      ],
      transit: [
        { nearestStationName: "Donggongon Bus Terminal", stationLine: "Bas Bandar Penampang", walkTimeMins: 4, distanceMeters: 280 },
      ],
    },

    // ─── Sarawak — Kuching District (NEW) ────────────────────
    {
      name: "Black Bean Bistro Kuching",
      googlePlaceId: "ChIJx0z5nLY6zDERqN2rBcImKjL",
      formattedAddress: "27, Jalan Carpenter, 93000 Kuching, Sarawak",
      category: "cafe",
      state: "Sarawak",
      district: "Kuching",
      area: "Kuching City",
      latitude: 1.5595,
      longitude: 110.3583,
      googleRating: 4.5,
      googleUserRatingsTotal: 1234,
      googleMapsUrl: "https://maps.google.com/?cid=9100000029",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
        operatingHours: "9:00-22:00",
      },
      venueCost: { coffeePriceMyr: 13.00, dayPassMyr: null, minSpendMyr: 12.00 },
      wifiMetrics: [
        { downloadMbps: 75, uploadMbps: 34, pingMs: 14 },
      ],
      transit: [],
    },

    // ─── Sarawak — Bintulu District (NEW) ────────────────────
    {
      name: "Bintulu Waterfront Cafe",
      googlePlaceId: "ChIJy1a6oLZ7zDERqN2rBcImKjL",
      formattedAddress: "Lot 4, Jalan Sultan Iskandar, 97000 Bintulu, Sarawak",
      category: "cafe",
      state: "Sarawak",
      district: "Bintulu",
      area: "Bintulu",
      latitude: 3.1700,
      longitude: 113.0400,
      googleRating: 4.1,
      googleUserRatingsTotal: 184,
      googleMapsUrl: "https://maps.google.com/?cid=9100000030",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "casual_sofa",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
        operatingHours: "10:00-22:00",
      },
      venueCost: { coffeePriceMyr: 10.00, dayPassMyr: null, minSpendMyr: 10.00 },
      wifiMetrics: [
        { downloadMbps: 42, uploadMbps: 18, pingMs: 22 },
      ],
      transit: [],
    },

    // ─── Negeri Sembilan — Port Dickson District (NEW) ───────
    {
      name: "PD Bay Beachfront Cafe",
      googlePlaceId: "ChIJz2b7pLa8zDERqN2rBcImKjL",
      formattedAddress: "Lot 12, Jalan Pantai, 71000 Port Dickson, Negeri Sembilan",
      category: "cafe",
      state: "Negeri Sembilan",
      district: "Port Dickson",
      area: "Port Dickson",
      latitude: 2.5228,
      longitude: 101.7969,
      googleRating: 4.2,
      googleUserRatingsTotal: 543,
      googleMapsUrl: "https://maps.google.com/?cid=9100000031",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "casual_sofa",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
        operatingHours: "10:00-22:00",
      },
      venueCost: { coffeePriceMyr: 12.00, dayPassMyr: null, minSpendMyr: 12.00 },
      wifiMetrics: [
        { downloadMbps: 52, uploadMbps: 23, pingMs: 20 },
      ],
      transit: [
        { nearestStationName: "PD Waterfront Bus Stop", stationLine: "Bas Port Dickson", walkTimeMins: 5, distanceMeters: 320 },
      ],
    },

    // ─── Pahang — Cameron Highlands District (NEW) ──────────
    {
      name: "Barrington Cafe Tanah Rata",
      googlePlaceId: "ChIJa3c8qLb9zDERqN2rBcImKjL",
      formattedAddress: "17, Jalan Besar, 39000 Tanah Rata, Cameron Highlands, Pahang",
      category: "cafe",
      state: "Pahang",
      district: "Cameron Highlands",
      area: "Tanah Rata",
      latitude: 4.4689,
      longitude: 101.3851,
      googleRating: 4.4,
      googleUserRatingsTotal: 876,
      googleMapsUrl: "https://maps.google.com/?cid=9100000032",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "quiet",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
        operatingHours: "8:00-21:00",
      },
      venueCost: { coffeePriceMyr: 14.00, dayPassMyr: null, minSpendMyr: 14.00 },
      wifiMetrics: [
        { downloadMbps: 58, uploadMbps: 26, pingMs: 18 },
      ],
      transit: [
        { nearestStationName: "Tanah Rata Bus Terminal", stationLine: "Bas Cameron Highlands", walkTimeMins: 4, distanceMeters: 280 },
      ],
    },
    {
      name: "Cameron Valley Tea House",
      googlePlaceId: "ChIJb4d9rLc0zDERqN2rBcImKjL",
      formattedAddress: "PT 44, Jalan Brinchang, 39100 Brinchang, Cameron Highlands, Pahang",
      category: "cafe",
      state: "Pahang",
      district: "Cameron Highlands",
      area: "Brinchang",
      latitude: 4.5222,
      longitude: 101.4136,
      googleRating: 4.3,
      googleUserRatingsTotal: 642,
      googleMapsUrl: "https://maps.google.com/?cid=9100000033",
      isOperational: true,
      workProfile: {
        powerOutlets: "sparse",
        noiseLevel: "moderate",
        seatingType: "casual_sofa",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
        operatingHours: "9:00-18:00",
      },
      venueCost: { coffeePriceMyr: 12.00, dayPassMyr: null, minSpendMyr: 12.00 },
      wifiMetrics: [
        { downloadMbps: 45, uploadMbps: 20, pingMs: 22 },
      ],
      transit: [],
    },

    // ─── Perak (NEW STATE) — Kinta District ──────────────────
    {
      name: "Burps and Giggles Ipoh",
      googlePlaceId: "ChIJc5e0sLd1zDERqN2rBcImKjL",
      formattedAddress: "15, Jalan Panglima, 30000 Ipoh, Perak",
      category: "cafe",
      state: "Perak",
      district: "Kinta",
      area: "Ipoh",
      latitude: 4.5975,
      longitude: 101.0907,
      googleRating: 4.5,
      googleUserRatingsTotal: 2104,
      googleMapsUrl: "https://maps.google.com/?cid=9100000034",
      isOperational: true,
      workProfile: {
        powerOutlets: "high",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
        operatingHours: "10:00-22:00",
      },
      venueCost: { coffeePriceMyr: 15.00, dayPassMyr: null, minSpendMyr: 15.00 },
      wifiMetrics: [
        { downloadMbps: 80, uploadMbps: 36, pingMs: 12 },
        { downloadMbps: 88, uploadMbps: 40, pingMs: 10 },
      ],
      transit: [
        { nearestStationName: "Stesen KTM Ipoh", stationLine: "KTM ETS", walkTimeMins: 7, distanceMeters: 500 },
      ],
    },

    // ─── Perak (NEW STATE) — Manjung District ───────────────
    {
      name: "Sitiawan Heritage Coffee",
      googlePlaceId: "ChIJe6f1tLe2zDERqN2rBcImKjL",
      formattedAddress: "42, Jalan Menglembu, 32000 Sitiawan, Perak",
      category: "cafe",
      state: "Perak",
      district: "Manjung",
      area: "Sitiawan",
      latitude: 4.2233,
      longitude: 100.6983,
      googleRating: 4.1,
      googleUserRatingsTotal: 234,
      googleMapsUrl: "https://maps.google.com/?cid=9100000035",
      isOperational: true,
      workProfile: {
        powerOutlets: "moderate",
        noiseLevel: "moderate",
        seatingType: "standard",
        laptopPolicy: "friendly_unlimited",
        hasAirCon: true,
        callFriendly: false,
        operatingHours: "8:00-21:00",
      },
      venueCost: { coffeePriceMyr: 9.00, dayPassMyr: null, minSpendMyr: 8.00 },
      wifiMetrics: [
        { downloadMbps: 42, uploadMbps: 18, pingMs: 24 },
      ],
      transit: [],
    },
  ]

  for (const loc of locations) {
    const location = await db.location.create({
      data: {
        googlePlaceId: loc.googlePlaceId,
        name: loc.name,
        formattedAddress: loc.formattedAddress,
        category: loc.category,
        state: loc.state,
        district: loc.district,
        area: loc.area,
        latitude: loc.latitude,
        longitude: loc.longitude,
        googleRating: loc.googleRating,
        googleUserRatingsTotal: loc.googleUserRatingsTotal,
        googleMapsUrl: loc.googleMapsUrl,
        isOperational: loc.isOperational,
        workProfile: {
          create: loc.workProfile,
        },
        venueCost: loc.venueCost ? {
          create: loc.venueCost,
        } : undefined,
      },
    })

    // Seed Wi-Fi metrics
    for (const wm of loc.wifiMetrics) {
      await db.wifiMetric.create({
        data: {
          locationId: location.id,
          ...wm,
        },
      })
    }

    // Seed transit links
    for (const tr of loc.transit) {
      await db.transitAccess.create({
        data: {
          locationId: location.id,
          ...tr,
        },
      })
    }
  }

  console.log(`✅ Seeded ${locations.length} locations across Malaysia`)
  console.log('📍 States covered:', [...new Set(locations.map(l => l.state))].join(', '))
}

seed()
  .catch(console.error)
  .finally(() => db.$disconnect())
